// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V3
    #ifndef UNIFFI_SHARED_HEADER_V3
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V3
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V3
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V3 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V3 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

void ffi_didcomm_rs_b50c_Message_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull didcomm_rs_b50c_Message_new(
      
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull didcomm_rs_b50c_Message_new_receive(
      RustBuffer incomming,RustBuffer sk,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer didcomm_rs_b50c_Message_get_to(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void didcomm_rs_b50c_Message_set_to(
      void*_Nonnull ptr,RustBuffer str,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer didcomm_rs_b50c_Message_get_from(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void didcomm_rs_b50c_Message_set_from(
      void*_Nonnull ptr,RustBuffer from,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer didcomm_rs_b50c_Message_get_body2(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void didcomm_rs_b50c_Message_set_body2(
      void*_Nonnull ptr,RustBuffer body,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer didcomm_rs_b50c_Message_as_raw_json2(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void didcomm_rs_b50c_Message_set_crypto_algorithm_xc20_p(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer didcomm_rs_b50c_Message_unwrap_base58_key(
      void*_Nonnull ptr,RustBuffer key,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer didcomm_rs_b50c_Message_seal2(
      void*_Nonnull ptr,RustBuffer sk,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer didcomm_rs_b50c_Message_set_routed_by(
      void*_Nonnull ptr,RustBuffer ekey,RustBuffer mediator_did_string,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_didcomm_rs_b50c_rustbuffer_alloc(
      int32_t size,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_didcomm_rs_b50c_rustbuffer_from_bytes(
      ForeignBytes bytes,
    RustCallStatus *_Nonnull out_status
    );
void ffi_didcomm_rs_b50c_rustbuffer_free(
      RustBuffer buf,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_didcomm_rs_b50c_rustbuffer_reserve(
      RustBuffer buf,int32_t additional,
    RustCallStatus *_Nonnull out_status
    );
